
name: 'FitLife'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
models:
  FitLife:
    # Applies to all files under models/example/
    +transient: false
    # las tablas transient no tienen Time Travel ni protección ante fallos. Este parámetro lo desactiva para que todas las tablas tengan protección completa. 
    staging:
      +materialized: view
      +database: "{{ env_var('DBT_ENVIRONMENTS', '_DEV_FITLIFE') }}_SILVER_DB"
      +schema: SILVER

    marts:
      +materialized: table
      +database: "{{ env_var('DBT_ENVIRONMENTS', '_DEV_FITLIFE') }}_GOLD_DB"
      +schema: GOLD
